import Head from "next/head";
import Image from "next/image";
import Hello from "@/components/Hello";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="">
          <h1 className="text-5xl text-red-500">
            Welcome to Next.js home page
          </h1>
          <Hello name="Azeem" />
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Id magni
            eligendi tempore, laudantium impedit alias recusandae quam corrupti
            consectetur, sed unde fuga quidem labore qui odit ad cupiditate?
            Consectetur, ipsum?
          </p>
        </div>
      </main>
    </>
  );
}
